<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <?php echo $this->headTitle(); ?>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Le styles -->
    <link href="<?php echo $this->baseUrl(); ?>/bootstrap/css/bootstrap.css" rel="stylesheet">
    <style type="text/css">
      body {
        padding-top: 60px;
        padding-bottom: 40px;
      }
      .sidebar-nav {
        padding: 9px 0;
      }
    </style>
    <link href="<?php echo $this->baseUrl(); ?>/bootstrap/css/bootstrap-responsive.css" rel="stylesheet">

    <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <!-- Le fav and touch icons -->
    <link rel="shortcut icon" href="<?php echo $this->baseUrl(); ?>/bootstrap/ico/favicon.ico">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="<?php echo $this->baseUrl(); ?>/bootstrap/ico/apple-touch-icon-114-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="<?php echo $this->baseUrl(); ?>/bootstrap/ico/apple-touch-icon-72-precomposed.png">
    <link rel="apple-touch-icon-precomposed" href="<?php echo $this->baseUrl(); ?>/bootstrap/ico/apple-touch-icon-57-precomposed.png">
  </head>

  <body>
    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">Zend Test</a>
          <div class="nav-collapse">
            <ul class="nav">
              <li class="active"><a href="<?php echo $this->baseUrl(); ?>/index.php">Home</a></li>
              <li><a href="<?php echo $this->baseUrl(); ?>/index.php/index/about">About</a></li>
              <li><a href="#contact">Contact</a></li>
            </ul>
            <p class="navbar-text pull-right">Logged in as <a href="#">username</a></p>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container-fluid">
      <div class="row-fluid">
        <div class="span3">
          <div class="well sidebar-nav">
            <ul class="nav nav-list">
              <li class="nav-header">Sidebar</li>
              <li class="active"><a href="#">Link</a></li>
              <li><a href="#">Link</a></li>
              <li><a href="#">Link</a></li>
              <li><a href="#">Link</a></li>
              <li class="nav-header">Sidebar</li>
              <li><a href="#">Link</a></li>
              <li><a href="#">Link</a></li>
              <li><a href="#">Link</a></li>
              <li><a href="#">Link</a></li>
              <li><a href="#">Link</a></li>
              <li><a href="#">Link</a></li>
              <li class="nav-header">Sidebar</li>
              <li><a href="#">Link</a></li>
              <li><a href="#">Link</a></li>
              <li><a href="#">Link</a></li>
            </ul>
          </div><!--/.well -->
        </div><!--/span--> <div class="span9"><?php echo $this->layout()->content; ?></div>
        <!--/span-->
      </div>
      <!--/row-->

      <hr>

      <footer>
        <p>&copy; Stephen Ng 2012</p>
      </footer>

    </div><!--/.fluid-container-->

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="<?php echo $this->baseUrl(); ?>/bootstrap/js/jquery.js"></script>
    <script src="<?php echo $this->baseUrl(); ?>/bootstrap/js/bootstrap-transition.js"></script>
    <script src="<?php echo $this->baseUrl(); ?>/bootstrap/js/bootstrap-alert.js"></script>
    <script src="<?php echo $this->baseUrl(); ?>/bootstrap/js/bootstrap-modal.js"></script>
    <script src="<?php echo $this->baseUrl(); ?>/bootstrap/js/bootstrap-dropdown.js"></script>
    <script src="<?php echo $this->baseUrl(); ?>/bootstrap/js/bootstrap-scrollspy.js"></script>
    <script src="<?php echo $this->baseUrl(); ?>/bootstrap/js/bootstrap-tab.js"></script>
    <script src="<?php echo $this->baseUrl(); ?>/bootstrap/js/bootstrap-tooltip.js"></script>
    <script src="<?php echo $this->baseUrl(); ?>/bootstrap/js/bootstrap-popover.js"></script>
    <script src="<?php echo $this->baseUrl(); ?>/bootstrap/js/bootstrap-button.js"></script>
    <script src="<?php echo $this->baseUrl(); ?>/bootstrap/js/bootstrap-collapse.js"></script>
    <script src="<?php echo $this->baseUrl(); ?>/bootstrap/js/bootstrap-carousel.js"></script>
    <script src="<?php echo $this->baseUrl(); ?>/bootstrap/js/bootstrap-typeahead.js"></script>

  </body>
</html>